//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vajehdan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vajehdan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ـ هـا (کتاب‌ها، کتابها،
        ///(کلاشینکوف) / کلاشینکف
        ///آئروبیک، آیروبیک
        ///آئروبیکی، آیروبیکی
        ///آئرودینامیک، آیرودینامیک
        ///آئروسل
        ///آئروفون
        ///آئرولیت
        ///آئینمند/ آئین‌مند
        ///آب آتش‌رنگ
        ///آب آتش‌فام
        ///آب آتشگون
        ///آب آتش‌مزاج
        ///آب آتشین
        ///آب آلبالو
        ///آب آلو
        ///آب آلوده
        ///آب آهک
        ///آب اکسیژنه
        ///آب اماله
        ///آب انار
        ///آب انارین
        ///آب انجیر
        ///آب اندک
        ///آب انگور
        ///آب ایستاده
        ///آب باتری/ آب باطری
        ///آب باریک
        ///آب برم
        ///آب بقا
        ///آب بینی
        ///آب پاکی
        ///آب پرتقال
        ///آب پشت
        ///آب تبلور
        ///آب تربت
        ///آب توبه
        ///آب جاری
        ///آب جوش
        ///آب چشم
        ///آب [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Emlaei {
            get {
                return ResourceManager.GetString("Emlaei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آب،ماء،مایع،شیره،عرق،عصاره،عصیر،حل،محلول،ذوب،خوی،بزاق،آب‌دهان،منی،بحر،دریا،یم،زهاب،آبرو،حیثیت،شرف،عزت،تری،تازگی،طراوت
        ///آباء،اجداد،اسلاف،پدران،پیشینیان،نیاکان،اخلاف
        ///آباجی،آبجی،اخت،باجی،خواهر،دده،شاباجی،همشیره،داداش
        ///آباد،برپا،دایر،معمور،پررونق،پیشرفته،توسعه‌یافته،مترقی،تندرست،سالم،بسامان،منظم،غنی،مرفه،خراب،متروک،ویران،بی‌رونق،عقب‌مانده
        ///آبادان،آباد،برپا،پررونق،دایر،معمور،خراب
        ///آبادانی،آبادی،عمارت،عمران،ترقی،توسعه،رونق،آسایش،ترفیه،رفاه،خرابی
        ///آبادی،آبادانی،عمارت،عمران،ده،دهات،دهکده،روستا،شهر،واحه،ولایت
        ///آبان [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Motaradef {
            get {
                return ResourceManager.GetString("Motaradef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) اجردهنده،تلافی‌کننده،پاداش‌دهنده،سخاوت‌آمیز،نظر بلند،سودآور،دارای ثواب،ثواب‌دار
        ///[ شامل بدیهای محیط و دنیای خارج از فرد است. در مورد صفات بد انسانی به رجوع شود.]،فلاکت،بدی،ناگوارایی،زشتی
        ///[اسم] بی‌جوهری،بی‌اساسی،عدم،مجازی بودن،مجرد بودن،انتزاعی بودن،معنویت،هیچ،صفر،هوا،سبکی،سطحی بودن،کم عمقی،خلاء،احمقانه بودن،امر محال،بی ربطی،فقدان ارتباط،توهم،فریب،ناملموس بودن،وهم،لاغری،باریکی
        ///[اسم] پاکدامنی،عفت،عفاف،پاکی،عصمت،معصومیت،بی‌گناهی،اخلاص،پرهیزگاری،فروتنی،امساک،اعتدال،خلوص،صافی،قاطی نداشتن،سادگی،تمیزی،پاکی،ط [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teyfi {
            get {
                return ResourceManager.GetString("Teyfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Vajehdan {
            get {
                object obj = ResourceManager.GetObject("Vajehdan", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
