//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vajehyar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vajehyar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبِ آتش‌رنگ
        ///آبِ آتش‌فام
        ///آبِ آتشگون
        ///آبِ آتش‌مزاج
        ///آبِ آتشین
        ///آب‌آزما(ی)
        ///آبِ آلبالو
        ///آب‌آلبالو
        ///آب‌آلو
        ///آبِ آلو
        ///آبِ آلوده
        ///آب‌آلویی/ آب‌آلوئی
        ///آب‌آوردگی
        ///آبِ آهک
        ///آب‌آهک
        ///آبادسازی
        ///آبادسالی
        ///آبادگر
        ///آبادی‌نشین
        ///آب‌ازسرگذشته
        ///آب‌اسید
        ///آب‌اکسیژن
        ///آبِ اکسیژنه
        ///آب‌اکسیژنه
        ///آبِ اِماله
        ///آبِ انار
        ///آبِ انارین
        ///آب‌انبار
        ///آب‌انباری
        ///آب‌انباشت
        ///آبِ انجیر
        ///آب‌اندازی
        ///آبِ اندک
        ///آبِ انگور
        ///آباواجدادی
        ///آبِ ایستاده
        ///آبایی/ آبائی
        ///آباءِ مسیحی
        ///آبِ باتری/ آبِ باطری
        ///آب‌باتری/ آب‌باطری
        ///آبِ باریک
        ///آب‌باریکه
        ///آب‌باز
        ///آب‌باز [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Emlaei {
            get {
                return ResourceManager.GetString("Emlaei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اب،ابو،باب،بابا،پدر،والد،ابن،ام
        ///ابا،امتناع،انکار،حاشا،احتراز،خودداری،سرپیچی،سرکشی،نافرمانی،تکبر،نخوت
        ///ابابیل،پرستو،چلچله
        ///اباحت،جایز شمردن،جواز،حلال‌کردن،روایی،مباح دانستن،تحریم
        ///اباطیل،اراجیف،اکاذیب،بیهوده‌ها،ترهات،مزخرفات،موهومات
        ///ابتدا،آغاز،اوان،اوایل،اول،بدو،شروع،عنفوان،مطلع،نخست،انتها
        ///ابتدایی،آغازین،اولی،بدوی،مقدماتی،نخستین،انتهایی
        ///ابتذال،بی‌ارزشی،بی‌قدری،پستی،پیش‌پاافتادگی
        ///ابتر،بلاعقب،بلاعقبه،بی‌اولاد،مقطوع‌النسل،ناتمام،ناقص،دم‌بریده
        ///ابتکار،ابداع،اختراع،بدعت،نوآوری،ذوق،قریحه،پگاه‌خیزی،سحرخیزی
        ///اب [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Motaradef_Motazad {
            get {
                return ResourceManager.GetString("Motaradef_Motazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگاه،آشنا،باخبر،بیدار،خبردار،خبره،خبیر،دانا،روشن‌ضمیر،شناسا،عارف،متنبه،متوجه،مخبر،مسبوق،مستحضر،مطلع،ملتفت،نبیه،وارد،واقف،هوشیار،ناآگاه
        ///آگاه‌کردن،آگاهاندن،آگاهانیدن،آگهی‌دادن،خبردادن،خبردارکردن،مستحضر‌ساختن،مطلع‌ساختن،باخبرکردن،بیدارکردن،واقف‌کردن،هوشیار‌ساختن،غافل‌کردن
        ///برخاستن،ایستادن،به‌پاخاستن،برپا‌شدن،بلند‌شدن،بیدار‌شدن،بردمیدن،سر زدن،برآمدن،طلوع‌کردن،شوریدن،شورش‌کردن،طغیان‌کردن،عصیان‌کردن،قیام‌کردن،متصاعد‌شدن،پدیدآمدن،آغاز‌شدن،در گرفتن،پیش آمدن،اتفاق افتادن
        ///بلند‌شدن،ایستادن،نشستن،برخاستن،پا‌شدن،نشستن [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود،بودن،کون،هستی،بقا،بود،ذات مطلق،وجود مطلق،ذات خداوندی،ذات،معاش،جان،نَفْس،زندگی،وجود درزمان،بقا،ابدیت،واقعیت،وجود ازپیش،تقدم،وجود درمکان،حضور،دارایی،به‌وجود آمدن،پیدایش،شدن،تکوین،تکامل،تبدیل،خلق،ایجاد،تولید،بالقوه بودن،امکان،نهفتگی،هستی‌شناسی،اُنتولوژی،بودشناسی،ماوراءالطبیعه،مابعدالطبیعه،واقع‌گرایی،ایده‌آلیسم،اگزیستانسیالیسم،فلسفه،ماده‌گرایی،ماتریالیسم،مادیت
        ///واقعیت،حقیقت داشتن،موجودیت،کیان،هستی،وجود واقعی،مادیت،آن بودن،خاص بودن،ویژگی،پوزیتیویته،واقع،فاکت،حقیقت،اتفاق افتادن،واقع شدن،وقوع،استقرار،فضای معی [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teyfi {
            get {
                return ResourceManager.GetString("Teyfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Vajehyar {
            get {
                object obj = ResourceManager.GetObject("Vajehyar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
