//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vajehyar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vajehyar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اب؛ابو،باب،بابا،پدر،والد≠ابن،ام
        ///ابا؛امتناع،انکار،حاشا|احتراز،خودداری|سرپیچی،سرکشی،نافرمانی|تکبر،نخوت
        ///ابابیل؛پرستو،چلچله
        ///اباحت؛جایز شمردن،جواز،حلال‌کردن،روایی،مباح دانستن≠تحریم
        ///اباطیل؛اراجیف،اکاذیب،بیهوده‌ها،ترهات،مزخرفات،موهومات
        ///ابتدا؛آغاز،اوان،اوایل،اول،بدو،شروع،عنفوان،مطلع،نخست≠انتها
        ///ابتدایی؛آغازین،اولی،بدوی،مقدماتی،نخستین≠انتهایی
        ///ابتذال؛بی‌ارزشی،بی‌قدری،پستی،پیش‌پاافتادگی
        ///ابتر؛بلاعقب،بلاعقبه،بی‌اولاد،مقطوع‌النسل|ناتمام،ناقص|دم‌بریده
        ///ابتکار؛ابداع،اختراع،بدعت،نوآوری|ذوق،قریحه|پگاه‌خیزی،سحرخیزی
        ///اب [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Motaradef_Motazad {
            get {
                return ResourceManager.GetString("Motaradef_Motazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود، بودن، کون، هستی، بقا، بود؛ ذات مطلق، وجود مطلق، ذات خداوندی؛ ذات؛ معاش، جان، نَفْس، زندگی؛ وجود درزمان، بقا، ابدیت، واقعیت؛ وجود ازپیش، تقدم؛ وجود درمکان، حضور؛ دارایی؛ به‌وجود آمدن، پیدایش، شدن، تکوین، تکامل، تبدیل؛ خلق، ایجاد، تولید؛ بالقوه بودن، امکان، نهفتگی؛ هستی‌شناسی، اُنتولوژی، بودشناسی، ماوراءالطبیعه، مابعدالطبیعه، واقع‌گرایی، ایده‌آلیسم، اگزیستانسیالیسم، فلسفه، ماده‌گرایی، ماتریالیسم، مادیت
        ///واقعیت، حقیقت داشتن، موجودیت، کیان، هستی؛ وجود واقعی، مادیت؛ آن بودن، خاص بودن، ویژگی؛ پوزیتیویته؛ وا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teyfi {
            get {
                return ResourceManager.GetString("Teyfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Vajehyar {
            get {
                object obj = ResourceManager.GetObject("Vajehyar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
